name: Test and Deploy on Docker image
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
    types:
      - closed
      
jobs:
  CD-Build-deploy:
    runs-on: ubuntu-latest
    env:
      KEY: '${{ secrets.KEY }}'
      ATLAS: '${{ secrets.ATLAS }}'
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          export ATLAS=${{ secrets.ATLAS }}
          export KEY=${{ secrets.KEY }}
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          export DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
          echo $DOCKER_USERNAME
          echo $DOCKER_PASSWORD
          echo $ATLAS
          echo $KEY
      - name: Run tests with pytest
        run: |
          pytest
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          export DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: z0s3r77/flaskapirestolivanders:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
