name: CI Flask App 
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  CI:
  #Se elige un RUNNER "especie de contenedor"
    runs-on:  ubuntu-latest
    env:
      KEY: '${{ secrets.KEY }}'
      ATLAS: '${{ secrets.ATLAS }}'
    steps:
    #Descargamos una copia del repositorio en el runner con el checkout
      - uses:  actions/checkout@v3

    #Instalamos Python, a la verión 3.10
      - name:  Installing Python 3.10
        uses:  actions/setup-python@v4.3.1
        with:
          python-verion: 3.10

    #Con está acción guardamos en caché las dependencias descargadas para mejorar la velociadad de ejecución del RUNNER
      - name: Caching pip cache
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

    #Instalamos dependencias (al tener el actions/cache@v3 no se instalan)
      - name:  Intalling dependencie
        run:  |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          export ATLAS=${{ secrets.ATLAS }}
          export KEY=${{ secrets.KEY }}


    #Lanzamos el comando Pytest
      - name: Running tox
        run:  |
          tox
